### ISSUE TITLE
Undo Option

### ISSUE THREAD

**Issue by BluePT** [Fs00/Win10BloatRemover#14]

**Comment by BluePT** [comment]
Please provide option to undo changes to default values.

**Comment by Fs00** [comment]
Hello @BluePT, this won't happen for the following reasons:
- it's something not trivial to implement and maintain for all operations (or at least many of them); it's also rarely useful in practice
- there is already a much preferable and safer alternative, which is [creating a system restore point](https://support.microsoft.com/en-us/windows/create-a-system-restore-point-77e02e2a-3298-c869-9974-ef5658ea3be9) before running the tool and then using it in case you want to revert the changes
