### ISSUE TITLE
uninstall only programs that i don't use.

### ISSUE THREAD

**Issue by spaceboyrunningfast** [Fs00/Win10BloatRemover#16]
add the possibility to be able to choose which programs to uninstall from the default ones that existed from the beginning in windows 10.

**Comment by Fs00** [comment]
Hello @spaceboyrunningfast, the program can already do this! :slightly_smiling_face:
To choose which apps you want to remove, you only need to edit the `UWPAppsToRemove` list in the configuration file (see the [Configuration section of the README](https://github.com/Fs00/Win10BloatRemover/blob/master/README.md#configuration) for more info).
