### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Decation2** [Fs00/Win10BloatRemover#9]
I'm want to add the disable cortana fuction

**Comment by Fs00** [comment]
Hello! The tool can already disable Cortana by removing its app.
You just need to run "Remove UWP apps" and make sure that `Cortana` is in the list of apps that will be removed (it should be present by default). If you remove the app for all users, the tool also hides the Cortana icon from the task bar.

**Comment by Decation2** [comment]
Add function to disable remote access to the computer from windows

**Comment by Fs00** [comment]
> Add function to disable remote access to the computer from windows

This is an interesting idea. I'm not 100% sure if it fits with the scope of the tool, but I'll consider adding it to the _Tweak settings for privacy_ operation (a new menu entry to change a single option seems overkill to me).
Thanks for the proposal!

**Comment by Fs00** [comment]
I've just checked and Remote Desktop is already disabled by default on Windows 10, so there is nothing to do here.
Thanks for the idea though!
